  
name: CI

on:
  pull_request: {branches: master}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Compile
        run: javac -cp "lib/*:." *.java
        working-directory: ${{env.working-directory}}
      - name: Test 
        run: java -cp "lib/*:." TestRunner
        working-directory: ${{env.working-directory}}